version: '3.3'

volumes:
    prometheus_data: {}
    cloudwatch_data: {}
    blackbox_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  cloudwatch:
    image: prom/cloudwatch-exporter:latest
    environment:
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - REGION=$REGION
      - OUTPUT=json
    ports:
      - 9106:9106
    volumes:
      - cloudwatch_data:/cloudwatch
      - ./cloudwatch/alb.yml:/config/alb.yml
    command:      
      - '/config/alb.yml'
    restart: always

  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - 9115:9115
    volumes:
      - blackbox_data:/blackbox
    restart: always

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 8080:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
